/**
 * Runtime map registry (plan 018 step A3) — the game-side consumption seam for authored map data.
 * Pure — no Phaser. `manifest.json` + `world.json` are eager-imported at module load (small,
 * needed for every `mapAt`/`originOf` query before any map is loaded); each `*.map.json` is a lazy
 * per-map chunk via `import.meta.glob`, so booting the game never pulls every map's tile/object
 * payload into one bundle.
 *
 * L0 note: `originOf` falls back to `{col:0,row:0}` for a map with no `world.json` placement — the
 * L0 start map is expected to be unplaced (single map, loads at the origin). Plan 019 (L1 map
 * streaming) requires every map that's actually reachable in-game to have a real placement; this
 * fallback stays L0-only.
 */

import {
  parseManifest,
  parseWorldLayout,
  buildWorldIndex,
  type MapPlacement,
  type MapMetaLite,
} from './worldLayout';
import { migrateMap, type MapFile } from './mapFormat';

import manifestJson from '../data/maps/manifest.json';
import worldJson from '../data/maps/world.json';

/** Parsed at module load — throws if either file fails validation (fail-fast at boot). */
export const MANIFEST = parseManifest(manifestJson);
export const WORLD = parseWorldLayout(worldJson);

const METAS: Record<string, MapMetaLite> = {};
for (const entry of MANIFEST.maps) {
  METAS[entry.id] = { id: entry.id, width: entry.width, height: entry.height };
}

/** Bbox-only index (no map files loaded) — `mapAt` degrades to a bbox match, `seams` returns `[]`
 *  until a map is also loaded into it (not needed at L0: see plan 019 for the loaded-`maps` upgrade
 *  path). */
export const WORLD_INDEX = buildWorldIndex(MANIFEST.placements, METAS);

/** `world.json` (not the generated `manifest.json` mirror) is the placement source of truth here —
 *  it's already eager-imported and is what the editor writes directly. */
function findPlacement(mapId: string): MapPlacement | undefined {
  return WORLD.placements.find((p) => p.mapId === mapId);
}

/** The placement origin for `mapId`, or `{col:0,row:0}` if it has none in `world.json` (see module
 *  doc — L0-only fallback for the unplaced start map). */
export function originOf(mapId: string): { col: number; row: number } {
  const placement = findPlacement(mapId);
  return placement ? placement.origin : { col: 0, row: 0 };
}

/** Lazy per-map loaders keyed by map id, derived from each glob-matched path's filename (strips the
 *  `src/data/maps/` dir and the `.map.json` suffix). `import: 'default'` narrows each loader's
 *  resolved value to the map JSON's default export (still `unknown` until `migrateMap`/`parseMap`
 *  validates it). */
const mapLoaders = new Map<string, () => Promise<unknown>>();
for (const [path, loader] of Object.entries(
  import.meta.glob<unknown>('../data/maps/*.map.json', { import: 'default' }),
)) {
  const match = /([^/]+)\.map\.json$/.exec(path);
  if (!match) continue; // defensive — every glob match should end in `<id>.map.json`
  mapLoaders.set(match[1], loader);
}

/** Dynamic-imports + validates `src/data/maps/<id>.map.json`. Throws if `id` has no matching file,
 *  or if the file fails `migrateMap`/`parseMap` validation. In DEV, also cross-checks the freshly
 *  parsed `meta` against this id's `MANIFEST.maps` entry (width/height/name) — `manifest.json` is a
 *  generated artifact regenerated by the editor's save middleware, so a mismatch means it's stale
 *  relative to this map file. Warns (doesn't throw) rather than calling `generateManifest` here,
 *  which needs every map loaded, not just this one. */
export async function loadMapFile(id: string): Promise<MapFile> {
  const loader = mapLoaders.get(id);
  if (!loader) throw new Error(`loadMapFile: no map file found for id "${id}"`);
  const raw = await loader();
  const map = migrateMap(raw);

  if (import.meta.env.DEV) {
    const entry = MANIFEST.maps.find((m) => m.id === id);
    if (!entry) {
      console.warn(
        `[mapRuntime] manifest.json has no entry for map "${id}" — regenerate it (editor save).`,
      );
    } else {
      const mismatches: string[] = [];
      if (entry.width !== map.meta.width) {
        mismatches.push(`width manifest=${entry.width} meta=${map.meta.width}`);
      }
      if (entry.height !== map.meta.height) {
        mismatches.push(`height manifest=${entry.height} meta=${map.meta.height}`);
      }
      if (entry.name !== map.meta.name) {
        mismatches.push(
          `name manifest=${JSON.stringify(entry.name)} meta=${JSON.stringify(map.meta.name)}`,
        );
      }
      if (mismatches.length > 0) {
        console.warn(
          `[mapRuntime] manifest.json is stale for map "${id}": ${mismatches.join(', ')} — ` +
            'regenerate it (editor save).',
        );
      }
    }
  }

  return map;
}
